Vyshniakov - task1
tearfulmerlin/hillel-practice1 pull request #3
Opened 2023-01-10 19:04 UTC by wwwowka

2023-01-13 23:42 UTC, tearfulmerlin commented on src/task1/task1.js
> +  }
ці 2 блоки модна об'єднати

2023-01-13 23:49 UTC, tearfulmerlin commented on src/task2/task2.js
> +  const newArr = Array.from(String(stringArr), (elem) => Number(elem));
String(stringArr) - можна замінити на stringArr
stringArr в тебе і так рядок

2023-01-13 23:53 UTC, tearfulmerlin commented on src/task2/task2.js
> +  if (arr.length > newArr.length) {
за яких умов довжина arr буде більша довжини newArr?

2023-01-13 23:56 UTC, tearfulmerlin commented on src/task3/createPrevArgSaver.js
> +    return history[history.length - 2];
тут можна створити одну тимчасову змінну і обійтись 
history.shift(); та history.push(arg); без history[history.length - 2]

2023-01-13 23:57 UTC, tearfulmerlin requested changes
потрібен незначний рефакторинг

2023-01-14 11:19 UTC, wwwowka commented on src/task2/task2.js
> +  const newArr = Array.from(String(stringArr), (elem) => Number(elem));
У 59 рядку я з string роблю number.

2023-01-15 08:56 UTC, wwwowka commented on src/task2/task2.js
> +  if (arr.length > newArr.length) {
Якщо нульовий елемент масиву нуль ([0, 1, 3, 7]), при конвертації (масив > рядок > число > рядок > масив),
нуль губиться і я його додаю примусово.

2023-01-15 09:12 UTC, wwwowka commented on src/task1/task1.js
> +  }
Об'єднав.

2023-01-15 10:59 UTC, wwwowka commented on src/task3/createPrevArgSaver.js
> +    return history[history.length - 2];
Переписав через тимчасову змінну.

2023-01-22 13:50 UTC, closed without merging